import type { Metadata } from 'next'
import { Inter, Montserrat, Fraunces } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'], weight: ['500', '700'], variable: '--font-montserrat' })
const fraunces = Fraunces({ subsets: ['latin'], weight: ['700'], variable: '--font-fraunces' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(montserrat.variable, fraunces.variable, 'font-montserrat text-sm text-dark-gray-blue font-medium h-full bg-secondary')}>{children}</body>
    </html>
  )
}
